version: "3"
services:
  docker:
    volumes:
      - ./content:/var/www/html/content:rw
      - ./site/accounts:/var/www/html/site/accounts:rw
      - ./media:/var/www/html/media:rw
      # - ./content:/var/www/localhost/htdocs/content:rw
      # - ./site/accounts:/var/www/localhost/htdocs/site/accounts:rw
      # - ./media:/var/www/localhost/htdocs/media:rw
      # - ./site:/var/www/localhost/htdocs/site
      # - ./assets:/var/www/localhost/htdocs/assets
    ports:
      - "3000:80"
    build:
      context: ./
    # volumes:
    #   - ../cms:/var/www/html/cms:rw
    #   - ./data/cms/content:/var/www/html/cms/content:rw
    #   - ./data/cms/accounts:/var/www/html/cms/site/accounts:rw
    environment:
      KIRBY_UID: "1000" # find out your own value with 'id -u'
      KIRBY_GID: "1000" # find out your own value with 'id -g'
